name: Makefile CI

on:
  push:
    branches: [ "arm64" ]
  pull_request:
    branches: [ "arm64" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4

    - name: Build IPA
      run: make ipa

    - name: Upload IPA
      uses: actions/upload-artifact@v4.3.3
      with:
          name: kfd
          path: ${{ github.workspace }}/kfd.ipa
