name: Makefile CI

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4

    - name: Run make
      run: make ipa

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: kfd
        path: kfd.ipa      
